/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        secondary: '#ffffff',
        surface: {
          app: 'var(--surface-app)',
          navbar: 'var(--surface-navbar)',
          card: 'var(--surface-card)',
          elevated: 'var(--surface-elevated)',
          input: 'var(--surface-input)',
          hover: 'var(--surface-hover)',
        },
        border: {
          default: 'var(--border-default)',
          strong: 'var(--border-strong)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          disabled: 'var(--text-disabled)',
        },
        stitch: {
          primary: 'var(--stitch-primary)',
          'on-primary': 'var(--stitch-on-primary)',
          secondary: 'var(--stitch-secondary)',
          'on-secondary': 'var(--stitch-on-secondary)',
          surface: 'var(--stitch-surface)',
          'on-surface': 'var(--stitch-on-surface)',
          'surface-variant': 'var(--stitch-surface-variant)',
          'on-surface-variant': 'var(--stitch-on-surface-variant)',
          outline: 'var(--stitch-outline)',
          'outline-variant': 'var(--stitch-outline-variant)',
          'surface-container-highest': 'var(--stitch-surface-container-highest)',
          'surface-container-high': 'var(--stitch-surface-container-high)',
          'surface-container': 'var(--stitch-surface-container)',
          'surface-container-low': 'var(--stitch-surface-container-low)',
          'surface-container-lowest': 'var(--stitch-surface-container-lowest)',
          'surface-dim': 'var(--stitch-surface-dim)',
          'inverse-surface': 'var(--stitch-inverse-surface)',
        }
      },
      fontFamily: {
        'display': ['Geist', 'sans-serif'],
        'display-mobile': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'headline-sm': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'body-sm': ['Geist', 'sans-serif'],
        'label-code': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display': ['64px', { lineHeight: '72px', letterSpacing: '-0.035em', fontWeight: '600' }],
        'display-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-lg': ['44px', { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '500' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.025em', fontWeight: '500' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'label-code': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '500' }],
      },
      spacing: {
        'gutter': '1.5rem',
        'gutter-sm': '1rem',
        'margin': '2rem',
        'margin-sm': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      }
    },
  },
  plugins: [],
}
